name = "ResilienceDecisionMaking"
uuid = "e4e67209-a09d-4b87-93df-521fd564896e"
authors = [
    "Jasper Behrensdorf <behrensdorf@irz.uni-hannover.de>",
    "Julian Salomon <salomon@irz.uni-hannover.de>",
    "Niklas Winnewisser <winnewisser@irz.uni-hannover.de>",
]
version = "1.0.0"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Combinatorics = "1.0.2"
ProgressMeter = "1.7.2"
Statistics = "1.9.0"
julia = "1.6, 1.9"
